@startuml streaming

skinparam guillemet false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam style strictuml
skinparam classArrowFontSize 10
skinparam classFontStyle bold
skinparam SwimlaneBorderThickness 0

skinparam activity {
  hide empty description
}

|\t|
start
if (Is classes available?) then ([Yes])
stop
else (\t[No])
|\n|
:Assign Teacher to class;
:Assign room to for class;
stop

@enduml